package gomicSocMedShared

import "os"

const (
	GOMIC_PATH_TO_LOG = "GOMIC_PATH_TO_LOG"

	GOMIC_BASIC_AUTH_PASS_HASH = "GOMIC_BASIC_AUTH_PASS_HASH"
	GOMIC_BASIC_AUTH_USER      = "GOMIC_BASIC_AUTH_USER"
	GOMIC_BASIC_AUTH_PASS      = "GOMIC_BASIC_AUTH_PASS"

	TWITTER_REPEAT_CONSUMER_KEY        = "TWITTER_REPEAT_CONSUMER_KEY"
	TWITTER_REPEAT_CONSUMER_SECRET     = "TWITTER_REPEAT_CONSUMER_SECRET"
	TWITTER_REPEAT_ACCESS_TOKEN        = "TWITTER_REPEAT_ACCESS_TOKEN"
	TWITTER_REPEAT_ACCESS_TOKEN_SECRET = "TWITTER_REPEAT_ACCESS_TOKEN_SECRET"
	TWITTER_ORIGIN_CONSUMER_KEY        = "TWITTER_ORIGIN_CONSUMER_KEY"
	TWITTER_ORIGIN_CONSUMER_SECRET     = "TWITTER_ORIGIN_CONSUMER_SECRET"
	TWITTER_ORIGIN_ACCESS_TOKEN        = "TWITTER_ORIGIN_ACCESS_TOKEN"
	TWITTER_ORIGIN_ACCESS_TOKEN_SECRET = "TWITTER_ORIGIN_ACCESS_TOKEN_SECRET"
	GOMIC_TUMBLR_CALLBACK_URL          = "GOMIC_TUMBLR_CALLBACK_URL"
	GOMIC_TUMBLR_BLOG_NAME             = "GOMIC_TUMBLR_BLOG_NAME"
	GOMIC_TUMBLR_CONSUMER_KEY          = "GOMIC_TUMBLR_CONSUMER_KEY"
	GOMIC_TUMBLR_CONSUMER_SECRET       = "GOMIC_TUMBLR_CONSUMER_SECRET"
	GOMIC_TUMBLR_TOKEN                 = "GOMIC_TUMBLR_TOKEN"
	GOMIC_TUMBLR_TOKEN_SECRET          = "GOMIC_TUMBLR_TOKEN_SECRET"

	FB_DEVABODE_ID        = "FB_DEVABODE_ID"
	FB_APPLICATION_ID     = "FB_APPLICATION_ID"
	FB_APPLICATION_SECRET = "FB_APPLICATION_SECRET"
	FB_CALLBACK_URL       = "FB_CALLBACK_URL"

	GOMIC_STAGE      = "GOMIC_STAGE"
	GOMIC_STAGE_PROD = "prod"

	DB_GOMIC_USER = "DB_GOMIC_USER"
	DB_GOMIC_PASS = "DB_GOMIC_PASS"
	DB_GOMIC_NAME = "DB_GOMIC_NAME"
	DB_GOMIC_HOST = "DB_GOMIC_HOST"

	TLS_CERT_PATH = "TLS_CERT_PATH"
	TLS_KEY_PATH  = "TLS_KEY_PATH"

	GOMIC_SOCMED_PROD_URL  = "GOMIC_SOCMED_PROD_URL"
	GOMIC_SOCMED_PROD_PORT = "GOMIC_SOCMED_PROD_PORT"

	CURRENT_REST_VERSION = "0.1"
	REST_BASE_PATH       = "gomic/socmed"

	REST_PATH_ECHO = "/echo"

	REST_PATH_PUBLISH_ALL = "/all/publish"

	REST_PATH_PUBLISH_TWITTER = "/twitter/publish"

	REST_PATH_PUBLISH_TUMBLER          = "/tumblr/publish"
	REST_PATH_PUBLISH_TUMBLER_CALLBACK = "/tumblr/callback"

	REST_PATH_PUBLISH_FACEBOOK          = "/facebook/publish"
	REST_PATH_FACEBOOK_CALLBACK         = "/facebook/callback"
	REST_PATH_FACEBOOK_GET_ACCESS_TOKEN = "/facebook/getAccessToken"
)

func Env(key string) string {
	return os.Getenv(key)
}

func IsProd() bool {
	return Env(GOMIC_STAGE) == GOMIC_STAGE_PROD
}
